version: '3.9'

services:
  database:
    container_name: anotaai
    image: postgres
    environment:
      POSTGRES_USER: anotaai
      POSTGRES_PASSWORD: anotaai
      POSTGRES_DB: anotaai
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    container_name: relations-rabbitmq
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
      - '15672:15672'